//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRescueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Admin
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }

        [NotMapped]
        public List<ServiceProvider> SPlist { get; set; }
        [NotMapped]
        public List<Catagory> Catagorylist { get; set; }
        [NotMapped]
        public Catagory Catagory { get; set; }
        [NotMapped]
        public ServiceProvider ServiseProvider { get; set; }

    }
}
