//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRescueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Emergency
    {
        public int Id { get; set; }
        [Required,Display(Name ="Reporter Name")]
        public string reporter_name { get; set; }
        [Required, Display(Name = "Reporter Mobile Number"), RegularExpression(@"^([0]{1})+([3]{1})+([0-9]{9})$",ErrorMessage ="phone number should be in 03xxxxxxxxx format")]
        public string reporter_phnumber { get; set; }
        [Required, Display(Name ="Emergency Title")]
        public string emergency_title { get; set; }
        [Required, Display(Name = "Emergency Catagory")]
        public Nullable<int> catagory_id { get; set; }
        [Required, Display(Name = "Emergency Location")]
        public string emergency_location { get; set; }
        [Required, Display(Name = "Emergency Detail")]
        public string emergency_detail { get; set; }
        public string status { get; set; }
        public Nullable<int> sp_id { get; set; }
        [Display(Name ="Remarks")]
        public string sp_remarks { get; set; }
        public string feedback { get; set; }
    }
}
