//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRescueSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartRescueSystemEntities : DbContext
    {
        public SmartRescueSystemEntities()
            : base("name=SmartRescueSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<Emergency> Emergencies { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
    }
}
